@startuml "logical-data-model"
skinparam Shadowing False
skinparam RoundCorner 10
skinparam DefaultFontColor DimGrey

skinparam Object {
    BackgroundColor DodgerBlue
    ArrowColor DimGrey
    BorderColor White
    FontColor White
    FontStyle Bold
    AttributeFontColor White
    StereotypeFontColor White
}

Object Flight {
    'This is a combination of carrier code and the three digits
    IATA Combined Code
    Departure Date & Time
    Arrival Data & Time
    Number of Seats
    Seat Price
}

Object Carrier {
    IATA Carrier Code
}

Object Airport {
    IATA Airport Code
    Name
    Time Zone
}

Object Person {
    First Name
    Last Name
    Passport
}

Object Booking {
    Price
    'if credit card is null booking is paid by Frequent Flyer Number
    Credit Card Number
    Frequent Flyer Number
}

Object Schedule
Object Agency 

Airport o-"*" Flight: Start Destination
Airport o-"*" Flight: End Destination

Flight "*"--"1" Schedule
Flight "*"-"*" Person: PNR
Carrier o-"1" Schedule

Person "1.9"--"*" Booking: Passenger
Person "*"-o Agency: Employee

Booking "*"--"1.*" Flight

@enduml